apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications
        image: northamerica-northeast2-docker.pkg.dev/lms-capstone-456217/fastapi-docker-repo/notif:v2
        ports:
        - containerPort: 8008