apiVersion: v1
kind: Service
metadata:
  name: customer-auth
spec:
  type: ClusterIP
  selector:
    app: customer-auth
  ports:
    - protocol: TCP
      port: 8001  # the external user is using this port
      targetPort: 8001  # the container's port where the app listens (must be different)